[db]
host = "db.supabase.co"
port = 5432
name = "postgres"
user = "postgres"
password = ""
sslmode = "require"

[auth]
provider = "supabase"

[storage]
provider = "supabase"

[functions]
provider = "supabase"

[realtime]
provider = "supabase"
