name: Auto Commit and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push if there are changes
        run: |
          git add .
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git commit -m "Auto commit: $(date)"
            git push
          fi